---
- name: nginx install & start services
  hosts: web-server
  become: true

  tasks:
  - name: install nginx
    yum:
      name: nginx
      state: latest

  - name: start nginx
    service:
     name: nginx
     state: started

  - name: Allow all access to tcp port 80
    ufw:
      rule: allow
      port: '80'
      proto: tcp